#!/bin/bash

tar=""
x=""
ch=""

while [[ $# -gt 0 ]]; do
	case "$1" in 
	-tar)
		tar="$2"
		echo "|$tar" >> ~/bin/other/tarefas.csv
		shift 2
		;;
	s)
		nl -ba ~/bin/other/tarefas.csv
		shift 1
		;;
	-x)
		x="$2"
		sed -i "${2}d" ~/bin/other/tarefas.csv
		nl -ba ~/bin/other/tarefas.csv
		shift 2
		;;
	-ch)
		ch=$2
		awk -F'|' -v linha="$ch" 'NR==linha {$1="[SS]"} {print}' OFS='|' ~/bin/other/tarefas.csv > ~/bin/other/tmp.csv
        mv ~/bin/other/tmp.csv ~/bin/other/tarefas.csv
		nl -ba ~/bin/other/tarefas.csv
		;;
	*)
		echo "ERRO: parâmetros passados"
		exit 1
		;;
	esac
done



