#!/bin/bash


if [ $# -eq 0 ]; then

	echo "Hoje é: " $(date +%d/%m/%Y)
	read res
	echo "|$res" >> ~/bin/tasks.csv

elif [ $1 == "check" ]; then

	awk -F'|' -v linha="$2" 'NR==linha {$1="SS"} {print}' OFS='|' ~/bin/tasks.csv > ~/bin/tmp.csv
	mv tmp.csv tasks.csv

	awk -F'|' '
		{
			prioridade = ($1 ~ /SS/) ? 0 : 1
			print prioridade "|" $0
		}
	' ~/bin/tasks.csv | sort -t'|' -k1,1n | cut -d'|' -f2- > tmp.csv
	mv tmp.csv ~/bin/tasks.csv
	
	nl -ba ~/bin/tasks.csv
elif [ $1 == "s" ]; then

	awk -F'|' '
		{
			prioridade = ($1 ~ /SS/) ? 0 : 1
			print prioridade "|" $0
		}
	' ~/bin/tasks.csv | sort -t'|' -k1,1n | cut -d'|' -f2- > tmp.csv
	mv tmp.csv ~/bin/tasks.csv

	nl -ba ~/bin/tasks.csv

elif [ $1 == "x" ]; then
	if [ -z $2 ]; then

		echo "Tem certeza que deseja esvaziar o documento? (S/N)"
		read -rsn1 res2
		if [ $res2 == "s" ]; then
			sed -i "${2}d" ~/bin/tasks.csv
		else
				echo Nada foi excluido....
		fi
	else
			sed -i "${2}d" ~/bin/tasks.csv
	fi
fi
